### ISSUE TITLE
How to use hive when building cli apps in dart 

### ISSUE THREAD

**Issue by shan-shaji** [isar/hive#1138]
**Question**
I am building a CLI application and i want to persist some data to local storage. But when i am trying to initialise Hive in mac i am getting the permission error. My question how is can i give the right path to save the data in both mac, windows and linux?

**Code sample**
```dart
Hive.init('/folder_name')
```

**Version**
 - Platform: Mac, Windows, Linux
 - Flutter version: 3.3.4
 - Hive version: 2.2.3

**Comment by Luismi74** [comment]
What about doing it this way?


```dart
import 'dart:io';
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';

void main() async {
 String homeDir = Directory.systemTemp.path;
  String appDir = Directory("${homeDir}/YourAppName").path;
  Hive.init(appDir);
 
  final box = await Hive.openBox('myBox');
  box.put('key', 'Hello, Hive!');
  var storedValue = box.get('key');
  print('Retrieved value: $storedValue');

  await box.close();
}

``` `

**Comment by shan-shaji** [comment]
Thanks, @Luismi74 I was able to solve this. Forgot to close the issue.
