### ISSUE TITLE
FIREBASE DocumentReference:  HiveError: Cannot write, unknown type: DocumentReference. Did you forget to register an adapter?

### ISSUE THREAD

**Issue by mrgnhnt96** [isar/hive#270]
**Steps to Reproduce**
I have created a class with a DocumentReference (Firebase), Hive is giving me an error saying that it the document reference needs to be registered, but I cannot register a DocumentReference. 

**Code sample**
Meal Class In "meal.dart"
```
class Meal {
  @HiveField(0)
  final double calories;
  @HiveField(1)
  final double carbs;
  @HiveField(2)
  final double fats;
  @HiveField(3)
  final String name;
  @HiveField(4)
  final double proteins;
  @HiveField(5)
  final DocumentReference recipe;
  @HiveField(6)
  final String season;
  @HiveField(7)
  final double servings;
  @HiveField(8)
  final String type;
  @HiveField(9)
  final String url;
  @HiveField(10)
  final String id;

  Meal({
    this.calories,
    this.carbs,
    this.fats,
    this.name,
    this.proteins,
    this.recipe,
    this.season,
    this.servings,
    this.type,
    this.url,
    this.id,
  });
}
```

meal.g.dart file
```// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'meal.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class MealAdapter extends TypeAdapter<Meal> {
  @override
  final typeId = 5;

  @override
  Meal read(BinaryReader reader) {
    var numOfFields = reader.readByte();
    var fields = <int, dynamic>{
      for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Meal(
      calories: fields[0] as double,
      carbs: fields[1] as double,
      fats: fields[2] as double,
      name: fields[3] as String,
      proteins: fields[4] as double,
      recipe: fields[5] as DocumentReference,
      season: fields[6] as String,
      servings: fields[7] as double,
      type: fields[8] as String,
      url: fields[9] as String,
      id: fields[10] as String,
    );
  }

  @override
  void write(BinaryWriter writer, Meal obj) {
    writer
      ..writeByte(11)
      ..writeByte(0)
      ..write(obj.calories)
      ..writeByte(1)
      ..write(obj.carbs)
      ..writeByte(2)
      ..write(obj.fats)
      ..writeByte(3)
      ..write(obj.name)
      ..writeByte(4)
      ..write(obj.proteins)
      ..writeByte(5)
      ..write(obj.recipe)
      ..writeByte(6)
      ..write(obj.season)
      ..writeByte(7)
      ..write(obj.servings)
      ..writeByte(8)
      ..write(obj.type)
      ..writeByte(9)
      ..write(obj.url)
      ..writeByte(10)
      ..write(obj.id);
  }
}
```

**Version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (3 available)

• No issues found!
```
 - Hive version: ^1.4.1+1

**Comment by Mravuri96** [comment]
Did you add
```dart
 Hive.registerAdapter<Meal>( MealAdapter(), );
```
 before the runApp() in main()?

**Comment by mrgnhnt96** [comment]
Yes I did, Hive is set up and working properly on the app, however with the
Firebase plugin, the class DocumentReference cannot be edited for hive.

**Comment by BasedMusa** [comment]
ROUGH IDEA (BUT WILL WORK):

I faced similar issues with `Type` and `IconData`. The best way would be to covert that DocumentReference into a Map object and try saving that. And then in your code you have to create a new constructor called `Meal.fromHive()` or whatever you want to call it. This constructor will be like your normal constructor except that it will take `Map documentReference` parameter instead of `this.recipe`. And then you would convert that JSON into a DocumentReference in your `Meal.fromHive()` constructor.

**Comment by dop3ch3f** [comment]
Yh you have to register a document reference type adapter or convert your this.recipe field from a document reference to say a map before saving it using hive.

**Comment by WillianSalceda** [comment]
@BasedMusa How do i do that? I need a documentReference to be stored in my local database (Hive, of course), because in the future it will be used inside the cloud database. Already searched how to do that, but no results. Could you please explain me a little bit more?

**Comment by codaveto** [comment]
Here's a workaround assuming the field might be nullable

Create this extension on String? (optional)

`DocumentReference? get asDocumentReference => this != null ? FirebaseFirestore.instance.doc(this!) : null;`

Taking your example we have field number 5 as a document reference we write it as a String? instead of a DocumentReference?:

`..write(obj.recipe?.path)`

and then update the reading part to this:

`recipe: (fields[5] as String?).asDocumentReference,` (assuming you have the extension method)

If the field is not nullable then remove the nullable checks. Hope it helps. Initially I made a documentreference adapter but that didn't work because it tries to write it as the private _JsonDocumentReference class and that we can not access. Either way this will work, just make sure when you're generating the code with annotations that you copy the generated code into a new file and keep it there (instead of generating it) so you don't lose the changes. And then make sure to keep it up to date.

**Comment by gOzaru** [comment]
> **Steps to Reproduce** I have created a class with a DocumentReference (Firebase), Hive is giving me an error saying that it the document reference needs to be registered, but I cannot register a DocumentReference.
> 
> **Code sample** Meal Class In "meal.dart"
> 
> ```
> class Meal {
>   @HiveField(0)
>   final double calories;
>   @HiveField(1)
>   final double carbs;
>   @HiveField(2)
>   final double fats;
>   @HiveField(3)
>   final String name;
>   @HiveField(4)
>   final double proteins;
>   @HiveField(5)
>   final DocumentReference recipe;
>   @HiveField(6)
>   final String season;
>   @HiveField(7)
>   final double servings;
>   @HiveField(8)
>   final String type;
>   @HiveField(9)
>   final String url;
>   @HiveField(10)
>   final String id;
> 
>   Meal({
>     this.calories,
>     this.carbs,
>     this.fats,
>     this.name,
>     this.proteins,
>     this.recipe,
>     this.season,
>     this.servings,
>     this.type,
>     this.url,
>     this.id,
>   });
> }
> ```
> 
> meal.g.dart file
> 
> ```
> 
> part of 'meal.dart';
> 
> // **************************************************************************
> // TypeAdapterGenerator
> // **************************************************************************
> 
> class MealAdapter extends TypeAdapter<Meal> {
>   @override
>   final typeId = 5;
> 
>   @override
>   Meal read(BinaryReader reader) {
>     var numOfFields = reader.readByte();
>     var fields = <int, dynamic>{
>       for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
>     };
>     return Meal(
>       calories: fields[0] as double,
>       carbs: fields[1] as double,
>       fats: fields[2] as double,
>       name: fields[3] as String,
>       proteins: fields[4] as double,
>       recipe: fields[5] as DocumentReference,
>       season: fields[6] as String,
>       servings: fields[7] as double,
>       type: fields[8] as String,
>       url: fields[9] as String,
>       id: fields[10] as String,
>     );
>   }
> 
>   @override
>   void write(BinaryWriter writer, Meal obj) {
>     writer
>       ..writeByte(11)
>       ..writeByte(0)
>       ..write(obj.calories)
>       ..writeByte(1)
>       ..write(obj.carbs)
>       ..writeByte(2)
>       ..write(obj.fats)
>       ..writeByte(3)
>       ..write(obj.name)
>       ..writeByte(4)
>       ..write(obj.proteins)
>       ..writeByte(5)
>       ..write(obj.recipe)
>       ..writeByte(6)
>       ..write(obj.season)
>       ..writeByte(7)
>       ..write(obj.servings)
>       ..writeByte(8)
>       ..write(obj.type)
>       ..writeByte(9)
>       ..write(obj.url)
>       ..writeByte(10)
>       ..write(obj.id);
>   }
> }
> ```
> 
> **Version**
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-US)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.43.2)
> [✓] Connected device (3 available)
> 
> • No issues found!
> ```
> 
> * Hive version: ^1.4.1+1

Bro, Hive can only use String and int
